package com.study.boke.model;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.question_id
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.sender
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Integer sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.receiver
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.type
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.gmt_create
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.is_read
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    private Integer isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.question_id
     *
     * @return the value of reply.question_id
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.question_id
     *
     * @param questionId the value for reply.question_id
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.sender
     *
     * @return the value of reply.sender
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.sender
     *
     * @param sender the value for reply.sender
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.receiver
     *
     * @return the value of reply.receiver
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.receiver
     *
     * @param receiver the value for reply.receiver
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.type
     *
     * @return the value of reply.type
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.type
     *
     * @param type the value for reply.type
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.gmt_create
     *
     * @return the value of reply.gmt_create
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.gmt_create
     *
     * @param gmtCreate the value for reply.gmt_create
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.is_read
     *
     * @return the value of reply.is_read
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.is_read
     *
     * @param isRead the value for reply.is_read
     *
     * @mbg.generated Sat Feb 29 21:24:36 GMT+08:00 2020
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }
}